name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - 'main'  # Change this to your desired branch

env:
  PROJECT_ID: 'vt-gcp-sandbox'
  REGION: 'asia-southeast1'
  FUNC_NAME: 'learn-action'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: '${{ env.PROJECT_ID }}'
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy ${{ env.FUNC_NAME }} \
            --gen2 \
            --runtime nodejs20 \
            --trigger-http \
            --allow-unauthenticated \
            --source backend \
            --entry-point=learnAction  \
            --region ${{ env.REGION }} \
            --memory=512MB \
            --timeout=600s
